import { EndFittingItem, GasSpringTypeDefinition, ErpMssqlConfig } from '../types/cad';

export const DEFAULT_FITTINGS: EndFittingItem[] = [
  {
    id: 'fitting_eyelet_8',
    name: 'Gözlü Mafsal (Eyelet) Ø8 mm',
    category: 'Mafsal',
    shapeType: 'eyelet',
    offsetLenMm: 20.0,
    holeDiaMm: 8.0,
    material: 'Alüminyum 6082-T6 / Çelik Dövme',
    color: '#1d4ed8',
    isCustom: false,
  },
  {
    id: 'fitting_ball_joint_m8',
    name: 'Bilyalı Mafsal (Ball Joint) DIN 71802 M8',
    category: 'Mafsal',
    shapeType: 'ball',
    offsetLenMm: 22.0,
    holeDiaMm: 8.0,
    threadSize: 'M8x1.25',
    material: 'Çinko Kaplı Dövme Çelik',
    color: '#2563eb',
    isCustom: false,
  },
  {
    id: 'fitting_clevis_fork',
    name: 'Çatal Mafsal (Clevis Fork) DIN 71752',
    category: 'Çatal',
    shapeType: 'clevis',
    offsetLenMm: 24.0,
    holeDiaMm: 8.0,
    threadSize: 'M8',
    material: 'Galvanizli Çelik',
    color: '#1e40af',
    isCustom: false,
  },
  {
    id: 'fitting_threaded_m8',
    name: 'Düz Dişli Mil Saplama M8',
    category: 'Dişli',
    shapeType: 'threaded',
    offsetLenMm: 15.0,
    threadSize: 'M8x1.25',
    material: 'C45 İslah Çeliği',
    color: '#3b82f6',
    isCustom: false,
  },
  {
    id: 'fitting_threaded_m10',
    name: 'Düz Dişli Mil Saplama M10',
    category: 'Dişli',
    shapeType: 'threaded',
    offsetLenMm: 18.0,
    threadSize: 'M10x1.5',
    material: 'C45 İslah Çeliği',
    color: '#3b82f6',
    isCustom: false,
  },
  {
    id: 'fitting_flange_square',
    name: 'Flanşlı Montaj Başlığı (Flanged End)',
    category: 'Flanş',
    shapeType: 'flange',
    offsetLenMm: 16.0,
    holeDiaMm: 6.5,
    material: 'Çelik Levha St 37',
    color: '#1d4ed8',
    isCustom: false,
  },
];

export const DEFAULT_GAS_SPRING_TYPES: GasSpringTypeDefinition[] = [
  {
    id: 'type_standard_push',
    name: 'Standart İtme Tipi (Push Type)',
    formulaType: 'push',
    description: 'En yaygın kullanılan standart itici gazlı amortisör. Mil açık konumda bekler.',
    kFactor: 1.35,
    deadLengthMm: 40.0,
    maxPressureBar: 180.0,
    oilDampingRatio: 0.12,
    tempMinC: -30,
    tempMaxC: 80,
    materialGrade: 'St 37-2BK Boru & C45 Sert Krom Kaplı Mil (Ra ≤ 0.1μm)',
  },
  {
    id: 'type_traction_pull',
    name: 'Çekme Tipi Amortisör (Traction / Pull Type)',
    formulaType: 'pull',
    description: 'Ters çalışan amortisör. Mil normalde tüp içine çekili durur, çekme kuvveti üretir.',
    kFactor: 1.28,
    deadLengthMm: 50.0,
    maxPressureBar: 160.0,
    oilDampingRatio: 0.15,
    tempMinC: -25,
    tempMaxC: 80,
    materialGrade: 'Hassas Çelik Boru & Kromajlı İslah Mili',
  },
  {
    id: 'type_lockable',
    name: 'Blokeli / Kilitlenebilir (Lockable - Bloc-o-Lift)',
    formulaType: 'lockable',
    description: 'Dahili piston pimi ile strok boyunca istenen herhangi bir noktada rijit veya yaylı kilitlenme.',
    kFactor: 1.40,
    deadLengthMm: 60.0,
    maxPressureBar: 200.0,
    oilDampingRatio: 0.20,
    tempMinC: -20,
    tempMaxC: 75,
    materialGrade: 'Dahili Baypas Valfli Çift Odalı Gövde',
  },
  {
    id: 'type_stainless_316',
    name: 'Paslanmaz Çelik AISI 316 (Marine & Chemical)',
    formulaType: 'stainless',
    description: 'Yat, denizcilik, gıda ve medikal endüstri için asit ve tuz korozyonuna tam dayanıklı V4A paslanmaz.',
    kFactor: 1.35,
    deadLengthMm: 40.0,
    maxPressureBar: 180.0,
    oilDampingRatio: 0.12,
    tempMinC: -40,
    tempMaxC: 90,
    materialGrade: 'AISI 316L / DIN 1.4404 Östenitik Paslanmaz Çelik',
  },
  {
    id: 'type_damper',
    name: 'Hidrolik Hız Damperi (Motion Damper)',
    formulaType: 'damper',
    description: 'İtme kuvveti yerine hareket hızını ve darbeyi sönümleyen hidrolik amortisör ünitesi.',
    kFactor: 1.15,
    deadLengthMm: 45.0,
    maxPressureBar: 60.0,
    oilDampingRatio: 0.85,
    tempMinC: -20,
    tempMaxC: 70,
    materialGrade: 'Yüksek Viskoziteli Hidrolik Yağ Dolumlu Çelik Gövde',
  },
];

export const DEFAULT_ERP_CONFIG: ErpMssqlConfig = {
  host: '192.168.1.100',
  port: 1433,
  database: 'ERP_PRODUCTION_DB',
  username: 'erp_bom_user',
  authType: 'sql_auth',
  erpSystem: 'logo_tiger',
  itemMasterTable: 'dbo.LG_001_ITEMS',
  bomTable: 'dbo.LG_001_STFICHE_BOM',
  autoSync: false,
  status: 'idle',
};
