import { EndFittingItem, GasSpringTypeDefinition, ErpMssqlConfig, SavedDesign, ErpStockItem, BomErpMappingRule } from '../types/cad';

export const DEFAULT_FITTINGS: EndFittingItem[] = [
  {
    id: 'fitting_eyelet_8',
    name: 'Gözlü Mafsal (Eyelet) Ø8 mm',
    category: 'Mafsal',
    shapeType: 'eyelet',
    offsetLenMm: 20.0,
    holeDiaMm: 8.0,
    material: 'Alüminyum 6082-T6 / Çelik Dövme',
    color: '#1d4ed8',
    isCustom: false,
  },
  {
    id: 'fitting_ball_joint_m8',
    name: 'Bilyalı Mafsal (Ball Joint) DIN 71802 M8',
    category: 'Mafsal',
    shapeType: 'ball',
    offsetLenMm: 22.0,
    holeDiaMm: 8.0,
    threadSize: 'M8x1.25',
    material: 'Çinko Kaplı Dövme Çelik',
    color: '#2563eb',
    isCustom: false,
  },
  {
    id: 'fitting_clevis_fork',
    name: 'Çatal Mafsal (Clevis Fork) DIN 71752',
    category: 'Çatal',
    shapeType: 'clevis',
    offsetLenMm: 24.0,
    holeDiaMm: 8.0,
    threadSize: 'M8',
    material: 'Galvanizli Çelik',
    color: '#1e40af',
    isCustom: false,
  },
  {
    id: 'fitting_threaded_m8',
    name: 'Düz Dişli Mil Saplama M8',
    category: 'Dişli',
    shapeType: 'threaded',
    offsetLenMm: 15.0,
    threadSize: 'M8x1.25',
    material: 'C45 İslah Çeliği',
    color: '#3b82f6',
    isCustom: false,
  },
  {
    id: 'fitting_threaded_m10',
    name: 'Düz Dişli Mil Saplama M10',
    category: 'Dişli',
    shapeType: 'threaded',
    offsetLenMm: 18.0,
    threadSize: 'M10x1.5',
    material: 'C45 İslah Çeliği',
    color: '#3b82f6',
    isCustom: false,
  },
  {
    id: 'fitting_flange_square',
    name: 'Flanşlı Montaj Başlığı (Flanged End)',
    category: 'Flanş',
    shapeType: 'flange',
    offsetLenMm: 16.0,
    holeDiaMm: 6.5,
    material: 'Çelik Levha St 37',
    color: '#1d4ed8',
    isCustom: false,
  },
];

export const DEFAULT_GAS_SPRING_TYPES: GasSpringTypeDefinition[] = [
  {
    id: 'type_standard_push',
    name: 'Standart İtme Tipi (Push Type)',
    formulaType: 'push',
    description: 'En yaygın kullanılan standart itici gazlı amortisör. Mil açık konumda bekler.',
    kFactor: 1.35,
    deadLengthMm: 40.0,
    maxPressureBar: 180.0,
    oilDampingRatio: 0.12,
    tempMinC: -30,
    tempMaxC: 80,
    materialGrade: 'St 37-2BK Boru & C45 Sert Krom Kaplı Mil (Ra ≤ 0.1μm)',
    isCustom: false,
    diameterRules: [
      { id: 'rule_15_6', tubeOd: 15, rodOd: 6, kFactor: 1.28, deadLengthMm: 35, maxPressureBar: 160, maxForceN: 400, tubeWallMm: 1.25, note: 'Hafif / Mobilya & Kapak' },
      { id: 'rule_18_8', tubeOd: 18, rodOd: 8, kFactor: 1.35, deadLengthMm: 40, maxPressureBar: 180, maxForceN: 800, tubeWallMm: 1.5, note: 'Standart Endüstriyel Seri' },
      { id: 'rule_22_10', tubeOd: 22, rodOd: 10, kFactor: 1.38, deadLengthMm: 45, maxPressureBar: 200, maxForceN: 1300, tubeWallMm: 1.5, note: 'Orta Yük Otomotiv / Makine' },
      { id: 'rule_28_14', tubeOd: 28, rodOd: 14, kFactor: 1.42, deadLengthMm: 50, maxPressureBar: 210, maxForceN: 2500, tubeWallMm: 1.75, note: 'Ağır Hizmet Makine Kapağı' },
      { id: 'rule_40_20', tubeOd: 40, rodOd: 20, kFactor: 1.50, deadLengthMm: 65, maxPressureBar: 240, maxForceN: 5000, tubeWallMm: 2.25, note: 'Ekstra Ağır Sanayi & Pres' },
    ],
  },
  {
    id: 'type_traction_pull',
    name: 'Çekme Tipi Amortisör (Traction / Pull Type)',
    formulaType: 'pull',
    description: 'Ters çalışan amortisör. Mil normalde tüp içine çekili durur, çekme kuvveti üretir.',
    kFactor: 1.28,
    deadLengthMm: 50.0,
    maxPressureBar: 160.0,
    oilDampingRatio: 0.15,
    tempMinC: -25,
    tempMaxC: 80,
    materialGrade: 'Hassas Çelik Boru & Kromajlı İslah Mili',
    isCustom: false,
    diameterRules: [
      { id: 'rule_tr_18_8', tubeOd: 18, rodOd: 8, kFactor: 1.26, deadLengthMm: 48, maxPressureBar: 150, maxForceN: 600, tubeWallMm: 1.5, note: 'Kompakt Çekme Tipi' },
      { id: 'rule_tr_28_10', tubeOd: 28, rodOd: 10, kFactor: 1.30, deadLengthMm: 55, maxPressureBar: 170, maxForceN: 1800, tubeWallMm: 2.0, note: 'Yüksek Çekme Kuvveti' },
    ],
  },
  {
    id: 'type_lockable',
    name: 'Blokeli / Kilitlenebilir (Lockable - Bloc-o-Lift)',
    formulaType: 'lockable',
    description: 'Dahili piston pimi ile strok boyunca istenen herhangi bir noktada rijit veya yaylı kilitlenme.',
    kFactor: 1.40,
    deadLengthMm: 60.0,
    maxPressureBar: 200.0,
    oilDampingRatio: 0.20,
    tempMinC: -20,
    tempMaxC: 75,
    materialGrade: 'Dahili Baypas Valfli Çift Odalı Gövde',
    isCustom: false,
    diameterRules: [
      { id: 'rule_loc_22_10', tubeOd: 22, rodOd: 10, kFactor: 1.38, deadLengthMm: 60, maxPressureBar: 200, maxForceN: 1000, tubeWallMm: 1.75, note: 'Medikal Yatak & Koltuk Kilit' },
      { id: 'rule_loc_28_10', tubeOd: 28, rodOd: 10, kFactor: 1.42, deadLengthMm: 65, maxPressureBar: 220, maxForceN: 1500, tubeWallMm: 2.0, note: 'Rijit Kilitleme' },
    ],
  },
  {
    id: 'type_stainless_316',
    name: 'Paslanmaz Çelik AISI 316 (Marine & Chemical)',
    formulaType: 'stainless',
    description: 'Yat, denizcilik, gıda ve medikal endüstri için asit ve tuz korozyonuna tam dayanıklı V4A paslanmaz.',
    kFactor: 1.35,
    deadLengthMm: 40.0,
    maxPressureBar: 180.0,
    oilDampingRatio: 0.12,
    tempMinC: -40,
    tempMaxC: 90,
    materialGrade: 'AISI 316L / DIN 1.4404 Östenitik Paslanmaz Çelik',
    isCustom: false,
    diameterRules: [
      { id: 'rule_ss_18_8', tubeOd: 18, rodOd: 8, kFactor: 1.35, deadLengthMm: 42, maxPressureBar: 180, maxForceN: 750, tubeWallMm: 1.75, note: 'Denizci Yat Lumbuz Kapağı' },
      { id: 'rule_ss_22_10', tubeOd: 22, rodOd: 10, kFactor: 1.40, deadLengthMm: 48, maxPressureBar: 200, maxForceN: 1200, tubeWallMm: 2.0, note: 'Gıda Reaktör Kapağı' },
    ],
  },
  {
    id: 'type_damper',
    name: 'Hidrolik Hız Damperi (Motion Damper)',
    formulaType: 'damper',
    description: 'İtme kuvveti yerine hareket hızını ve darbeyi sönümleyen hidrolik amortisör ünitesi.',
    kFactor: 1.15,
    deadLengthMm: 45.0,
    maxPressureBar: 60.0,
    oilDampingRatio: 0.85,
    tempMinC: -20,
    tempMaxC: 70,
    materialGrade: 'Yüksek Viskoziteli Hidrolik Yağ Dolumlu Çelik Gövde',
    isCustom: false,
    diameterRules: [
      { id: 'rule_dmp_18_8', tubeOd: 18, rodOd: 8, kFactor: 1.15, deadLengthMm: 45, maxPressureBar: 60, maxForceN: 500, tubeWallMm: 1.5, note: 'Hafif Kapak Frenleme' },
      { id: 'rule_dmp_28_14', tubeOd: 28, rodOd: 14, kFactor: 1.20, deadLengthMm: 55, maxPressureBar: 90, maxForceN: 1500, tubeWallMm: 2.0, note: 'Ağır Koruma Kalkanı Freni' },
    ],
  },
];

export const DEFAULT_SAVED_DESIGNS: SavedDesign[] = [
  {
    id: 'dsg_001_cabinet',
    code: 'DSG-2026-001',
    name: 'Endüstriyel Elektrik Panosu Üst Kapağı',
    customerOrProject: 'Siemens Sanayi / Kontrol Panelleri',
    createdAt: '2026-09-15T09:30:00Z',
    updatedAt: '2026-10-01T14:20:00Z',
    currentRevId: 'REV-02',
    tags: ['Elektrik Panosu', 'Ø18/8', 'Gözlü Mafsal', 'Hafif Sanayi'],
    revisions: [
      {
        revId: 'REV-01',
        timestamp: '2026-09-15T09:30:00Z',
        author: 'Ahmet Yılmaz (Mühendis)',
        notes: 'İlk konsept tasarım. 120mm strok ve 300N kuvvet ile hesaplandı.',
        params: {
          tubeOd: 18,
          rodOd: 8,
          stroke: 120,
          extLength: 300,
          forceN: 300,
          rodFittingId: 'fitting_eyelet_8',
          tubeFittingId: 'fitting_eyelet_8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-18-08-0120-0300-300N-EYE-EYE',
          extLength: 300,
          stroke: 120,
          forceN: 300,
          tubeOd: 18,
          rodOd: 8,
          requiredPressureBar: 59.7,
          f2Force: 405.0,
          kFactor: 1.35,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
      {
        revId: 'REV-02',
        timestamp: '2026-10-01T14:20:00Z',
        author: 'Ahmet Yılmaz (Mühendis)',
        notes: 'Kapak açılma açısı 85°den 105°ye çıkarıldı. Strok 150mm, Açık Boy 350mm ve F1 400N olarak revize edildi.',
        params: {
          tubeOd: 18,
          rodOd: 8,
          stroke: 150,
          extLength: 350,
          forceN: 400,
          rodFittingId: 'fitting_eyelet_8',
          tubeFittingId: 'fitting_eyelet_8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-18-08-0150-0350-400N-EYE-EYE',
          extLength: 350,
          stroke: 150,
          forceN: 400,
          tubeOd: 18,
          rodOd: 8,
          requiredPressureBar: 79.6,
          f2Force: 540.0,
          kFactor: 1.35,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
    ],
  },
  {
    id: 'dsg_002_tractor_hood',
    code: 'DSG-2026-002',
    name: 'Tarım Traktörü Motor Kaputu Kaldırıcı',
    customerOrProject: 'Türk Traktör / Tier-5 Motor Projesi',
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-09-28T16:45:00Z',
    currentRevId: 'REV-03',
    tags: ['Tarım Makineleri', 'Ø22/10', 'Bilyalı Mafsal', 'Ağır Hizmet'],
    revisions: [
      {
        revId: 'REV-01',
        timestamp: '2026-08-20T11:00:00Z',
        author: 'Mehmet Demir (CAD Uzmanı)',
        notes: 'Ön tasarım: 200mm strok, 600N.',
        params: {
          tubeOd: 22,
          rodOd: 10,
          stroke: 200,
          extLength: 480,
          forceN: 600,
          rodFittingId: 'fitting_ball_joint_m8',
          tubeFittingId: 'fitting_ball_joint_m8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-22-10-0200-0480-600N-BAL-BAL',
          extLength: 480,
          stroke: 200,
          forceN: 600,
          tubeOd: 22,
          rodOd: 10,
          requiredPressureBar: 76.4,
          f2Force: 828.0,
          kFactor: 1.38,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
      {
        revId: 'REV-02',
        timestamp: '2026-09-10T15:10:00Z',
        author: 'Mehmet Demir (CAD Uzmanı)',
        notes: 'Kaput yalıtım süngeri eklendiği için ağırlık arttı, F1 750N yapıldı.',
        params: {
          tubeOd: 22,
          rodOd: 10,
          stroke: 200,
          extLength: 480,
          forceN: 750,
          rodFittingId: 'fitting_ball_joint_m8',
          tubeFittingId: 'fitting_ball_joint_m8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-22-10-0200-0480-750N-BAL-BAL',
          extLength: 480,
          stroke: 200,
          forceN: 750,
          tubeOd: 22,
          rodOd: 10,
          requiredPressureBar: 95.5,
          f2Force: 1035.0,
          kFactor: 1.38,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
      {
        revId: 'REV-03',
        timestamp: '2026-09-28T16:45:00Z',
        author: 'Selin Kaya (Başmühendis)',
        notes: 'Saha titreşim testinde DIN 71802 bilyalı mafsal emniyet klipsli modele geçirildi, açık boy 500mm strok 210mm yapıldı.',
        params: {
          tubeOd: 22,
          rodOd: 10,
          stroke: 210,
          extLength: 500,
          forceN: 800,
          rodFittingId: 'fitting_ball_joint_m8',
          tubeFittingId: 'fitting_ball_joint_m8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-22-10-0210-0500-800N-BAL-BAL',
          extLength: 500,
          stroke: 210,
          forceN: 800,
          tubeOd: 22,
          rodOd: 10,
          requiredPressureBar: 101.9,
          f2Force: 1104.0,
          kFactor: 1.38,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
    ],
  },
  {
    id: 'dsg_003_marine_hatch',
    code: 'DSG-2026-003',
    name: 'Yat Güverte Ambar Kapağı (Paslanmaz)',
    customerOrProject: 'Sirena Marine / 58ft Motor Yacht',
    createdAt: '2026-09-05T08:15:00Z',
    updatedAt: '2026-09-05T08:15:00Z',
    currentRevId: 'REV-01',
    tags: ['Marin', 'Paslanmaz AISI 316', 'Ø22/10', 'Denizcilik'],
    revisions: [
      {
        revId: 'REV-01',
        timestamp: '2026-09-05T08:15:00Z',
        author: 'Caner Öz (Yat Tasarım)',
        notes: 'Tuzlu suya dayanıklı AISI 316L paslanmaz amortisör. 250mm strok, 550N.',
        params: {
          tubeOd: 22,
          rodOd: 10,
          stroke: 250,
          extLength: 580,
          forceN: 550,
          rodFittingId: 'fitting_eyelet_8',
          tubeFittingId: 'fitting_eyelet_8',
          springTypeId: 'type_stainless_316',
        },
        calcSnapshot: {
          partNumber: 'GSS-22-10-0250-0580-550N-EYE-EYE',
          extLength: 580,
          stroke: 250,
          forceN: 550,
          tubeOd: 22,
          rodOd: 10,
          requiredPressureBar: 70.0,
          f2Force: 770.0,
          kFactor: 1.40,
          springTypeName: 'Paslanmaz Çelik AISI 316 (Marine & Chemical)',
        },
      },
    ],
  },
];

export const DEFAULT_ERP_CONFIG: ErpMssqlConfig = {
  host: '192.168.1.100',
  port: 1433,
  database: 'ERP_PRODUCTION_DB',
  username: 'erp_bom_user',
  authType: 'sql_auth',
  erpSystem: 'logo_tiger',
  itemMasterTable: 'dbo.LG_001_ITEMS',
  bomTable: 'dbo.LG_001_STFICHE_BOM',
  autoSync: false,
  status: 'idle',
};

export const DEFAULT_ERP_STOCK_ITEMS: ErpStockItem[] = [
  // Borular (Tubes)
  { stockCode: '150.01.0015', stockName: 'Ø15x1.25mm Hassas Soğuk Çekme Dikişsiz Boru St 37-2BK', stockGroup: 'BORU', unit: 'METRE', inStockQty: 480, priceTry: 85 },
  { stockCode: '150.01.0018', stockName: 'Ø18x1.50mm Hassas Soğuk Çekme Dikişsiz Boru St 37-2BK', stockGroup: 'BORU', unit: 'METRE', inStockQty: 1250, priceTry: 110 },
  { stockCode: '150.01.0022', stockName: 'Ø22x1.50mm Hassas Soğuk Çekme Dikişsiz Boru St 37-2BK', stockGroup: 'BORU', unit: 'METRE', inStockQty: 890, priceTry: 145 },
  { stockCode: '150.01.0028', stockName: 'Ø28x1.75mm Hassas Soğuk Çekme Dikişsiz Boru St 37-2BK', stockGroup: 'BORU', unit: 'METRE', inStockQty: 620, priceTry: 210 },
  { stockCode: '150.01.0040', stockName: 'Ø40x2.25mm Ağır Hizmet Dikişsiz Silindir Borusu St 52', stockGroup: 'BORU', unit: 'METRE', inStockQty: 340, priceTry: 380 },
  { stockCode: '150.02.0018', stockName: 'Ø18x1.75mm Dikişsiz Paslanmaz Çelik Boru AISI 316L', stockGroup: 'BORU', unit: 'METRE', inStockQty: 180, priceTry: 320 },
  { stockCode: '150.02.0022', stockName: 'Ø22x2.00mm Dikişsiz Paslanmaz Çelik Boru AISI 316L', stockGroup: 'BORU', unit: 'METRE', inStockQty: 140, priceTry: 450 },

  // Miller (Piston Rods)
  { stockCode: '152.01.0006', stockName: 'Ø6mm C45 İslahlı Sert Krom Kaplı Piston Mili (Ra≤0.1)', stockGroup: 'MIL', unit: 'METRE', inStockQty: 350, priceTry: 75 },
  { stockCode: '152.01.0008', stockName: 'Ø8mm C45 İslahlı Sert Krom Kaplı Piston Mili (Ra≤0.1)', stockGroup: 'MIL', unit: 'METRE', inStockQty: 1400, priceTry: 95 },
  { stockCode: '152.01.0010', stockName: 'Ø10mm C45 İslahlı Sert Krom Kaplı Piston Mili (Ra≤0.1)', stockGroup: 'MIL', unit: 'METRE', inStockQty: 920, priceTry: 130 },
  { stockCode: '152.01.0014', stockName: 'Ø14mm 20MnV6 Taşlanmış Sert Kromlu Piston Mili', stockGroup: 'MIL', unit: 'METRE', inStockQty: 540, priceTry: 220 },
  { stockCode: '152.01.0020', stockName: 'Ø20mm 20MnV6 Taşlanmış Sert Kromlu Piston Mili', stockGroup: 'MIL', unit: 'METRE', inStockQty: 290, priceTry: 390 },
  { stockCode: '152.02.0008', stockName: 'Ø8mm AISI 316 Paslanmaz Çelik Taşlanmış Parlak Mil', stockGroup: 'MIL', unit: 'METRE', inStockQty: 220, priceTry: 260 },
  { stockCode: '152.02.0010', stockName: 'Ø10mm AISI 316 Paslanmaz Çelik Taşlanmış Parlak Mil', stockGroup: 'MIL', unit: 'METRE', inStockQty: 160, priceTry: 340 },

  // Uç Bağlantıları (Fittings)
  { stockCode: '170.01.0008', stockName: 'Gözlü Mafsal (Eyelet) Ø8mm Delik - Alüminyum 6082-T6', stockGroup: 'MAFSAL', unit: 'ADET', inStockQty: 2500, priceTry: 35 },
  { stockCode: '170.01.0010', stockName: 'Bilyalı Mafsal (Ball Joint) DIN 71802 M8 - Galvanizli Çelik', stockGroup: 'MAFSAL', unit: 'ADET', inStockQty: 1800, priceTry: 42 },
  { stockCode: '170.01.0012', stockName: 'Çatal Mafsal (Clevis Fork) DIN 71752 M8x16 - Çinko Kaplı', stockGroup: 'MAFSAL', unit: 'ADET', inStockQty: 950, priceTry: 48 },
  { stockCode: '170.01.0015', stockName: 'Düz Dişli Mil Ucu Saplama M8x1.25x15mm C45', stockGroup: 'MAFSAL', unit: 'ADET', inStockQty: 3200, priceTry: 18 },
  { stockCode: '170.01.0018', stockName: 'Düz Dişli Mil Ucu Saplama M10x1.50x18mm C45', stockGroup: 'MAFSAL', unit: 'ADET', inStockQty: 1600, priceTry: 24 },
  { stockCode: '170.01.0020', stockName: 'Flanşlı Kare Montaj Başlığı St 37 40x40mm', stockGroup: 'MAFSAL', unit: 'ADET', inStockQty: 450, priceTry: 65 },

  // Sızdırmazlık Keçe Paketleri (Seals)
  { stockCode: '180.01.1506', stockName: 'Sızdırmazlık Paketi Ø15/6mm (Poliüretan NBR + PTFE Kılavuz)', stockGroup: 'KECE', unit: 'TAKIM', inStockQty: 850, priceTry: 60 },
  { stockCode: '180.01.1808', stockName: 'Sızdırmazlık Paketi Ø18/8mm (Poliüretan NBR + PTFE Kılavuz)', stockGroup: 'KECE', unit: 'TAKIM', inStockQty: 3100, priceTry: 72 },
  { stockCode: '180.01.2210', stockName: 'Sızdırmazlık Paketi Ø22/10mm (Poliüretan NBR + PTFE Kılavuz)', stockGroup: 'KECE', unit: 'TAKIM', inStockQty: 1900, priceTry: 88 },
  { stockCode: '180.01.2814', stockName: 'Sızdırmazlık Paketi Ø28/14mm (Ağır Hizmet NBR + Çift Kılavuz)', stockGroup: 'KECE', unit: 'TAKIM', inStockQty: 750, priceTry: 125 },
  { stockCode: '180.01.4020', stockName: 'Sızdırmazlık Paketi Ø40/20mm (Yüksek Basınç Viton/PTFE)', stockGroup: 'KECE', unit: 'TAKIM', inStockQty: 320, priceTry: 240 },

  // Piston Başı ve Valfler
  { stockCode: '185.01.0008', stockName: 'Dinamik Orifisli Sönümleme Piston Başı Ø8mm Mil', stockGroup: 'VALF', unit: 'ADET', inStockQty: 2400, priceTry: 28 },
  { stockCode: '185.01.0010', stockName: 'Dinamik Orifisli Sönümleme Piston Başı Ø10mm Mil', stockGroup: 'VALF', unit: 'ADET', inStockQty: 1500, priceTry: 36 },
  { stockCode: '185.02.0010', stockName: 'Kilitlenebilir Blokaj Baypas Kontrol Subabı Ø10mm', stockGroup: 'VALF', unit: 'ADET', inStockQty: 400, priceTry: 165 },

  // Gaz ve Yağ
  { stockCode: '190.01.0001', stockName: 'Saf Azot Gazı (N2 %99.999 Saflıkta Dolum Gazı)', stockGroup: 'GAZ_YAG', unit: 'BAR', inStockQty: 85000, priceTry: 0.8 },
  { stockCode: '190.02.0001', stockName: 'Özel Amortisör Hidrolik Sönümleme Yağı ISO VG 15', stockGroup: 'GAZ_YAG', unit: 'LITRE', inStockQty: 450, priceTry: 180 },
];

export const DEFAULT_BOM_ERP_MAPPINGS: BomErpMappingRule[] = [
  { id: 'map_t_15', cadItemPrefix: 'RAW-TUBE-15', erpStockCode: '150.01.0015', erpStockName: 'Ø15x1.25mm Dikişsiz Boru' },
  { id: 'map_t_18', cadItemPrefix: 'RAW-TUBE-18', erpStockCode: '150.01.0018', erpStockName: 'Ø18x1.50mm Dikişsiz Boru' },
  { id: 'map_t_22', cadItemPrefix: 'RAW-TUBE-22', erpStockCode: '150.01.0022', erpStockName: 'Ø22x1.50mm Dikişsiz Boru' },
  { id: 'map_t_28', cadItemPrefix: 'RAW-TUBE-28', erpStockCode: '150.01.0028', erpStockName: 'Ø28x1.75mm Dikişsiz Boru' },
  { id: 'map_t_40', cadItemPrefix: 'RAW-TUBE-40', erpStockCode: '150.01.0040', erpStockName: 'Ø40x2.25mm Silindir Borusu' },

  { id: 'map_r_6', cadItemPrefix: 'RAW-ROD-6', erpStockCode: '152.01.0006', erpStockName: 'Ø6mm Sert Krom Kaplı Mil' },
  { id: 'map_r_8', cadItemPrefix: 'RAW-ROD-8', erpStockCode: '152.01.0008', erpStockName: 'Ø8mm Sert Krom Kaplı Mil' },
  { id: 'map_r_10', cadItemPrefix: 'RAW-ROD-10', erpStockCode: '152.01.0010', erpStockName: 'Ø10mm Sert Krom Kaplı Mil' },
  { id: 'map_r_14', cadItemPrefix: 'RAW-ROD-14', erpStockCode: '152.01.0014', erpStockName: 'Ø14mm Sert Kromlu Mil' },
  { id: 'map_r_20', cadItemPrefix: 'RAW-ROD-20', erpStockCode: '152.01.0020', erpStockName: 'Ø20mm Sert Kromlu Mil' },

  { id: 'map_f_eye', cadItemPrefix: 'FIT-ROD-FITTING_EYELET_8', erpStockCode: '170.01.0008', erpStockName: 'Gözlü Mafsal Ø8mm' },
  { id: 'map_f_ball', cadItemPrefix: 'FIT-ROD-FITTING_BALL_JOINT_M8', erpStockCode: '170.01.0010', erpStockName: 'Bilyalı Mafsal M8' },
  { id: 'map_f_clev', cadItemPrefix: 'FIT-ROD-FITTING_CLEVIS_FORK', erpStockCode: '170.01.0012', erpStockName: 'Çatal Mafsal DIN 71752 M8' },
  { id: 'map_f_th8', cadItemPrefix: 'FIT-ROD-FITTING_THREADED_M8', erpStockCode: '170.01.0015', erpStockName: 'Düz Dişli Mil Ucu M8' },
  { id: 'map_f_th10', cadItemPrefix: 'FIT-ROD-FITTING_THREADED_M10', erpStockCode: '170.01.0018', erpStockName: 'Düz Dişli Mil Ucu M10' },

  { id: 'map_ft_eye', cadItemPrefix: 'FIT-TUBE-FITTING_EYELET_8', erpStockCode: '170.01.0008', erpStockName: 'Gözlü Mafsal Ø8mm' },
  { id: 'map_ft_ball', cadItemPrefix: 'FIT-TUBE-FITTING_BALL_JOINT_M8', erpStockCode: '170.01.0010', erpStockName: 'Bilyalı Mafsal M8' },
  { id: 'map_ft_clev', cadItemPrefix: 'FIT-TUBE-FITTING_CLEVIS_FORK', erpStockCode: '170.01.0012', erpStockName: 'Çatal Mafsal DIN 71752 M8' },

  { id: 'map_s_15_6', cadItemPrefix: 'SEAL-KIT-15-6', erpStockCode: '180.01.1506', erpStockName: 'Sızdırmazlık Paketi Ø15/6' },
  { id: 'map_s_18_8', cadItemPrefix: 'SEAL-KIT-18-8', erpStockCode: '180.01.1808', erpStockName: 'Sızdırmazlık Paketi Ø18/8' },
  { id: 'map_s_22_10', cadItemPrefix: 'SEAL-KIT-22-10', erpStockCode: '180.01.2210', erpStockName: 'Sızdırmazlık Paketi Ø22/10' },
  { id: 'map_s_28_14', cadItemPrefix: 'SEAL-KIT-28-14', erpStockCode: '180.01.2814', erpStockName: 'Sızdırmazlık Paketi Ø28/14' },
  { id: 'map_s_40_20', cadItemPrefix: 'SEAL-KIT-40-20', erpStockCode: '180.01.4020', erpStockName: 'Sızdırmazlık Paketi Ø40/20' },

  { id: 'map_v_8', cadItemPrefix: 'VALVE-PISTON-8', erpStockCode: '185.01.0008', erpStockName: 'Dinamik Orifisli Piston Başı Ø8' },
  { id: 'map_v_10', cadItemPrefix: 'VALVE-PISTON-10', erpStockCode: '185.01.0010', erpStockName: 'Dinamik Orifisli Piston Başı Ø10' },

  { id: 'map_gas_n2', cadItemPrefix: 'GAS-N2-CHARGE', erpStockCode: '190.01.0001', erpStockName: 'Saf Azot Gazı N2 Dolumu' },
];
