import { EndFittingItem, GasSpringTypeDefinition, ErpMssqlConfig, SavedDesign } from '../types/cad';

export const DEFAULT_FITTINGS: EndFittingItem[] = [
  {
    id: 'fitting_eyelet_8',
    name: 'Gözlü Mafsal (Eyelet) Ø8 mm',
    category: 'Mafsal',
    shapeType: 'eyelet',
    offsetLenMm: 20.0,
    holeDiaMm: 8.0,
    material: 'Alüminyum 6082-T6 / Çelik Dövme',
    color: '#1d4ed8',
    isCustom: false,
  },
  {
    id: 'fitting_ball_joint_m8',
    name: 'Bilyalı Mafsal (Ball Joint) DIN 71802 M8',
    category: 'Mafsal',
    shapeType: 'ball',
    offsetLenMm: 22.0,
    holeDiaMm: 8.0,
    threadSize: 'M8x1.25',
    material: 'Çinko Kaplı Dövme Çelik',
    color: '#2563eb',
    isCustom: false,
  },
  {
    id: 'fitting_clevis_fork',
    name: 'Çatal Mafsal (Clevis Fork) DIN 71752',
    category: 'Çatal',
    shapeType: 'clevis',
    offsetLenMm: 24.0,
    holeDiaMm: 8.0,
    threadSize: 'M8',
    material: 'Galvanizli Çelik',
    color: '#1e40af',
    isCustom: false,
  },
  {
    id: 'fitting_threaded_m8',
    name: 'Düz Dişli Mil Saplama M8',
    category: 'Dişli',
    shapeType: 'threaded',
    offsetLenMm: 15.0,
    threadSize: 'M8x1.25',
    material: 'C45 İslah Çeliği',
    color: '#3b82f6',
    isCustom: false,
  },
  {
    id: 'fitting_threaded_m10',
    name: 'Düz Dişli Mil Saplama M10',
    category: 'Dişli',
    shapeType: 'threaded',
    offsetLenMm: 18.0,
    threadSize: 'M10x1.5',
    material: 'C45 İslah Çeliği',
    color: '#3b82f6',
    isCustom: false,
  },
  {
    id: 'fitting_flange_square',
    name: 'Flanşlı Montaj Başlığı (Flanged End)',
    category: 'Flanş',
    shapeType: 'flange',
    offsetLenMm: 16.0,
    holeDiaMm: 6.5,
    material: 'Çelik Levha St 37',
    color: '#1d4ed8',
    isCustom: false,
  },
];

export const DEFAULT_GAS_SPRING_TYPES: GasSpringTypeDefinition[] = [
  {
    id: 'type_standard_push',
    name: 'Standart İtme Tipi (Push Type)',
    formulaType: 'push',
    description: 'En yaygın kullanılan standart itici gazlı amortisör. Mil açık konumda bekler.',
    kFactor: 1.35,
    deadLengthMm: 40.0,
    maxPressureBar: 180.0,
    oilDampingRatio: 0.12,
    tempMinC: -30,
    tempMaxC: 80,
    materialGrade: 'St 37-2BK Boru & C45 Sert Krom Kaplı Mil (Ra ≤ 0.1μm)',
    isCustom: false,
    diameterRules: [
      { id: 'rule_15_6', tubeOd: 15, rodOd: 6, kFactor: 1.28, deadLengthMm: 35, maxPressureBar: 160, maxForceN: 400, tubeWallMm: 1.25, note: 'Hafif / Mobilya & Kapak' },
      { id: 'rule_18_8', tubeOd: 18, rodOd: 8, kFactor: 1.35, deadLengthMm: 40, maxPressureBar: 180, maxForceN: 800, tubeWallMm: 1.5, note: 'Standart Endüstriyel Seri' },
      { id: 'rule_22_10', tubeOd: 22, rodOd: 10, kFactor: 1.38, deadLengthMm: 45, maxPressureBar: 200, maxForceN: 1300, tubeWallMm: 1.5, note: 'Orta Yük Otomotiv / Makine' },
      { id: 'rule_28_14', tubeOd: 28, rodOd: 14, kFactor: 1.42, deadLengthMm: 50, maxPressureBar: 210, maxForceN: 2500, tubeWallMm: 1.75, note: 'Ağır Hizmet Makine Kapağı' },
      { id: 'rule_40_20', tubeOd: 40, rodOd: 20, kFactor: 1.50, deadLengthMm: 65, maxPressureBar: 240, maxForceN: 5000, tubeWallMm: 2.25, note: 'Ekstra Ağır Sanayi & Pres' },
    ],
  },
  {
    id: 'type_traction_pull',
    name: 'Çekme Tipi Amortisör (Traction / Pull Type)',
    formulaType: 'pull',
    description: 'Ters çalışan amortisör. Mil normalde tüp içine çekili durur, çekme kuvveti üretir.',
    kFactor: 1.28,
    deadLengthMm: 50.0,
    maxPressureBar: 160.0,
    oilDampingRatio: 0.15,
    tempMinC: -25,
    tempMaxC: 80,
    materialGrade: 'Hassas Çelik Boru & Kromajlı İslah Mili',
    isCustom: false,
    diameterRules: [
      { id: 'rule_tr_18_8', tubeOd: 18, rodOd: 8, kFactor: 1.26, deadLengthMm: 48, maxPressureBar: 150, maxForceN: 600, tubeWallMm: 1.5, note: 'Kompakt Çekme Tipi' },
      { id: 'rule_tr_28_10', tubeOd: 28, rodOd: 10, kFactor: 1.30, deadLengthMm: 55, maxPressureBar: 170, maxForceN: 1800, tubeWallMm: 2.0, note: 'Yüksek Çekme Kuvveti' },
    ],
  },
  {
    id: 'type_lockable',
    name: 'Blokeli / Kilitlenebilir (Lockable - Bloc-o-Lift)',
    formulaType: 'lockable',
    description: 'Dahili piston pimi ile strok boyunca istenen herhangi bir noktada rijit veya yaylı kilitlenme.',
    kFactor: 1.40,
    deadLengthMm: 60.0,
    maxPressureBar: 200.0,
    oilDampingRatio: 0.20,
    tempMinC: -20,
    tempMaxC: 75,
    materialGrade: 'Dahili Baypas Valfli Çift Odalı Gövde',
    isCustom: false,
    diameterRules: [
      { id: 'rule_loc_22_10', tubeOd: 22, rodOd: 10, kFactor: 1.38, deadLengthMm: 60, maxPressureBar: 200, maxForceN: 1000, tubeWallMm: 1.75, note: 'Medikal Yatak & Koltuk Kilit' },
      { id: 'rule_loc_28_10', tubeOd: 28, rodOd: 10, kFactor: 1.42, deadLengthMm: 65, maxPressureBar: 220, maxForceN: 1500, tubeWallMm: 2.0, note: 'Rijit Kilitleme' },
    ],
  },
  {
    id: 'type_stainless_316',
    name: 'Paslanmaz Çelik AISI 316 (Marine & Chemical)',
    formulaType: 'stainless',
    description: 'Yat, denizcilik, gıda ve medikal endüstri için asit ve tuz korozyonuna tam dayanıklı V4A paslanmaz.',
    kFactor: 1.35,
    deadLengthMm: 40.0,
    maxPressureBar: 180.0,
    oilDampingRatio: 0.12,
    tempMinC: -40,
    tempMaxC: 90,
    materialGrade: 'AISI 316L / DIN 1.4404 Östenitik Paslanmaz Çelik',
    isCustom: false,
    diameterRules: [
      { id: 'rule_ss_18_8', tubeOd: 18, rodOd: 8, kFactor: 1.35, deadLengthMm: 42, maxPressureBar: 180, maxForceN: 750, tubeWallMm: 1.75, note: 'Denizci Yat Lumbuz Kapağı' },
      { id: 'rule_ss_22_10', tubeOd: 22, rodOd: 10, kFactor: 1.40, deadLengthMm: 48, maxPressureBar: 200, maxForceN: 1200, tubeWallMm: 2.0, note: 'Gıda Reaktör Kapağı' },
    ],
  },
  {
    id: 'type_damper',
    name: 'Hidrolik Hız Damperi (Motion Damper)',
    formulaType: 'damper',
    description: 'İtme kuvveti yerine hareket hızını ve darbeyi sönümleyen hidrolik amortisör ünitesi.',
    kFactor: 1.15,
    deadLengthMm: 45.0,
    maxPressureBar: 60.0,
    oilDampingRatio: 0.85,
    tempMinC: -20,
    tempMaxC: 70,
    materialGrade: 'Yüksek Viskoziteli Hidrolik Yağ Dolumlu Çelik Gövde',
    isCustom: false,
    diameterRules: [
      { id: 'rule_dmp_18_8', tubeOd: 18, rodOd: 8, kFactor: 1.15, deadLengthMm: 45, maxPressureBar: 60, maxForceN: 500, tubeWallMm: 1.5, note: 'Hafif Kapak Frenleme' },
      { id: 'rule_dmp_28_14', tubeOd: 28, rodOd: 14, kFactor: 1.20, deadLengthMm: 55, maxPressureBar: 90, maxForceN: 1500, tubeWallMm: 2.0, note: 'Ağır Koruma Kalkanı Freni' },
    ],
  },
];

export const DEFAULT_SAVED_DESIGNS: SavedDesign[] = [
  {
    id: 'dsg_001_cabinet',
    code: 'DSG-2026-001',
    name: 'Endüstriyel Elektrik Panosu Üst Kapağı',
    customerOrProject: 'Siemens Sanayi / Kontrol Panelleri',
    createdAt: '2026-09-15T09:30:00Z',
    updatedAt: '2026-10-01T14:20:00Z',
    currentRevId: 'REV-02',
    tags: ['Elektrik Panosu', 'Ø18/8', 'Gözlü Mafsal', 'Hafif Sanayi'],
    revisions: [
      {
        revId: 'REV-01',
        timestamp: '2026-09-15T09:30:00Z',
        author: 'Ahmet Yılmaz (Mühendis)',
        notes: 'İlk konsept tasarım. 120mm strok ve 300N kuvvet ile hesaplandı.',
        params: {
          tubeOd: 18,
          rodOd: 8,
          stroke: 120,
          extLength: 300,
          forceN: 300,
          rodFittingId: 'fitting_eyelet_8',
          tubeFittingId: 'fitting_eyelet_8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-18-08-0120-0300-300N-EYE-EYE',
          extLength: 300,
          stroke: 120,
          forceN: 300,
          tubeOd: 18,
          rodOd: 8,
          requiredPressureBar: 59.7,
          f2Force: 405.0,
          kFactor: 1.35,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
      {
        revId: 'REV-02',
        timestamp: '2026-10-01T14:20:00Z',
        author: 'Ahmet Yılmaz (Mühendis)',
        notes: 'Kapak açılma açısı 85°den 105°ye çıkarıldı. Strok 150mm, Açık Boy 350mm ve F1 400N olarak revize edildi.',
        params: {
          tubeOd: 18,
          rodOd: 8,
          stroke: 150,
          extLength: 350,
          forceN: 400,
          rodFittingId: 'fitting_eyelet_8',
          tubeFittingId: 'fitting_eyelet_8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-18-08-0150-0350-400N-EYE-EYE',
          extLength: 350,
          stroke: 150,
          forceN: 400,
          tubeOd: 18,
          rodOd: 8,
          requiredPressureBar: 79.6,
          f2Force: 540.0,
          kFactor: 1.35,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
    ],
  },
  {
    id: 'dsg_002_tractor_hood',
    code: 'DSG-2026-002',
    name: 'Tarım Traktörü Motor Kaputu Kaldırıcı',
    customerOrProject: 'Türk Traktör / Tier-5 Motor Projesi',
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-09-28T16:45:00Z',
    currentRevId: 'REV-03',
    tags: ['Tarım Makineleri', 'Ø22/10', 'Bilyalı Mafsal', 'Ağır Hizmet'],
    revisions: [
      {
        revId: 'REV-01',
        timestamp: '2026-08-20T11:00:00Z',
        author: 'Mehmet Demir (CAD Uzmanı)',
        notes: 'Ön tasarım: 200mm strok, 600N.',
        params: {
          tubeOd: 22,
          rodOd: 10,
          stroke: 200,
          extLength: 480,
          forceN: 600,
          rodFittingId: 'fitting_ball_joint_m8',
          tubeFittingId: 'fitting_ball_joint_m8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-22-10-0200-0480-600N-BAL-BAL',
          extLength: 480,
          stroke: 200,
          forceN: 600,
          tubeOd: 22,
          rodOd: 10,
          requiredPressureBar: 76.4,
          f2Force: 828.0,
          kFactor: 1.38,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
      {
        revId: 'REV-02',
        timestamp: '2026-09-10T15:10:00Z',
        author: 'Mehmet Demir (CAD Uzmanı)',
        notes: 'Kaput yalıtım süngeri eklendiği için ağırlık arttı, F1 750N yapıldı.',
        params: {
          tubeOd: 22,
          rodOd: 10,
          stroke: 200,
          extLength: 480,
          forceN: 750,
          rodFittingId: 'fitting_ball_joint_m8',
          tubeFittingId: 'fitting_ball_joint_m8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-22-10-0200-0480-750N-BAL-BAL',
          extLength: 480,
          stroke: 200,
          forceN: 750,
          tubeOd: 22,
          rodOd: 10,
          requiredPressureBar: 95.5,
          f2Force: 1035.0,
          kFactor: 1.38,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
      {
        revId: 'REV-03',
        timestamp: '2026-09-28T16:45:00Z',
        author: 'Selin Kaya (Başmühendis)',
        notes: 'Saha titreşim testinde DIN 71802 bilyalı mafsal emniyet klipsli modele geçirildi, açık boy 500mm strok 210mm yapıldı.',
        params: {
          tubeOd: 22,
          rodOd: 10,
          stroke: 210,
          extLength: 500,
          forceN: 800,
          rodFittingId: 'fitting_ball_joint_m8',
          tubeFittingId: 'fitting_ball_joint_m8',
          springTypeId: 'type_standard_push',
        },
        calcSnapshot: {
          partNumber: 'GS-22-10-0210-0500-800N-BAL-BAL',
          extLength: 500,
          stroke: 210,
          forceN: 800,
          tubeOd: 22,
          rodOd: 10,
          requiredPressureBar: 101.9,
          f2Force: 1104.0,
          kFactor: 1.38,
          springTypeName: 'Standart İtme Tipi (Push Type)',
        },
      },
    ],
  },
  {
    id: 'dsg_003_marine_hatch',
    code: 'DSG-2026-003',
    name: 'Yat Güverte Ambar Kapağı (Paslanmaz)',
    customerOrProject: 'Sirena Marine / 58ft Motor Yacht',
    createdAt: '2026-09-05T08:15:00Z',
    updatedAt: '2026-09-05T08:15:00Z',
    currentRevId: 'REV-01',
    tags: ['Marin', 'Paslanmaz AISI 316', 'Ø22/10', 'Denizcilik'],
    revisions: [
      {
        revId: 'REV-01',
        timestamp: '2026-09-05T08:15:00Z',
        author: 'Caner Öz (Yat Tasarım)',
        notes: 'Tuzlu suya dayanıklı AISI 316L paslanmaz amortisör. 250mm strok, 550N.',
        params: {
          tubeOd: 22,
          rodOd: 10,
          stroke: 250,
          extLength: 580,
          forceN: 550,
          rodFittingId: 'fitting_eyelet_8',
          tubeFittingId: 'fitting_eyelet_8',
          springTypeId: 'type_stainless_316',
        },
        calcSnapshot: {
          partNumber: 'GSS-22-10-0250-0580-550N-EYE-EYE',
          extLength: 580,
          stroke: 250,
          forceN: 550,
          tubeOd: 22,
          rodOd: 10,
          requiredPressureBar: 70.0,
          f2Force: 770.0,
          kFactor: 1.40,
          springTypeName: 'Paslanmaz Çelik AISI 316 (Marine & Chemical)',
        },
      },
    ],
  },
];

export const DEFAULT_ERP_CONFIG: ErpMssqlConfig = {
  host: '192.168.1.100',
  port: 1433,
  database: 'ERP_PRODUCTION_DB',
  username: 'erp_bom_user',
  authType: 'sql_auth',
  erpSystem: 'logo_tiger',
  itemMasterTable: 'dbo.LG_001_ITEMS',
  bomTable: 'dbo.LG_001_STFICHE_BOM',
  autoSync: false,
  status: 'idle',
};
